### ISSUE TITLE
Typed Columns

### ISSUE THREAD

**Issue by adamdecaf** [Banno/banno-csv#3]
It would be nice to be able to return an actual type for a column rather than String. 

```
"Name", "Count"
"Bob", 1
```

**Comment by tbrown1979** [comment]
Did we decide this probably shouldn't happen? For example the string "1999" would be turned into an Int even though maybe the client wants it as a string. This should probably just be left up to them.

**Comment by InfernoJJ** [comment]
Here's an example for not auto turning stuff into ints. "058".
The context is this is an ID not a number. Turning this into a number will strip the 0. This needs to be left a string.

**Comment by adamdecaf** [comment]
Yea, I say we leave it all as strings. Votes?

**Comment by tbrown1979** [comment]
:+1: on leaving it as strings.
